# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>SkillStack India – Empowering Digital Growth</title>
  <style>
    *{margin:0;padding:0;box-sizing:border-box;font-family:"Poppins",sans-serif;}
    body{background:linear-gradient(180deg,#e6f0ff,#ffffff);color:#0a2540;}
    header{background:#0a2540;color:#fff;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;padding:1rem 2rem;}
    .logo{height:40px;}
    nav a{color:#fff;margin:0 1rem;text-decoration:none;font-weight:500;}
    nav a:hover{text-decoration:underline;}
    .hero{padding:4rem 2rem;text-align:center;background:linear-gradient(135deg,#1a4dba,#00aaff);color:#fff;border-radius:0 0 30px 30px;}
    .hero span{color:#fdcb26;}
    .btn{background:#fdcb26;color:#0a2540;padding:.8rem 1.5rem;border:none;border-radius:10px;font-weight:600;cursor:pointer;margin:.5rem;}
    .btn:hover{background:#ffdf6b;}
    section{padding:2rem;text-align:center;}
    h2{color:#1a4dba;margin-bottom:1rem;}
    p{margin:.5rem 0;line-height:1.6;}
    .card{background:#fff;max-width:850px;margin:1.5rem auto;padding:1.5rem;border-radius:20px;box-shadow:0 4px 12px rgba(0,0,0,.1);}
    footer{background:#0a2540;color:#fff;text-align:center;padding:1rem;margin-top:3rem;border-radius:30px 30px 0 0;}
    @media(max-width:600px){header{flex-direction:column;align-items:flex-start;}nav a{margin:.5rem 0;display:block;}}
  </style>
</head>
<body>
  <header>
    <img src="https://i.ibb.co/pb0z4Rn/skillstack-logo.png" alt="SkillStack India Logo" class="logo">
    <nav>
      <a href="#home">Home</a>
      <a href="#about">About</a>
      <a href="#products">Products</a>
      <a href="#contact">Contact</a>
    </nav>
  </header>

  <section id="home" class="hero">
    <h1>Welcome to <span>SkillStack India</span></h1>
    <p>Empowering creators, freelancers, and entrepreneurs with modern digital tools.</p>
    <p style="font-weight:600;">एक कदम डिजिटल इंडिया की ओर 🇮🇳</p>
    <button class="btn" onclick="document.getElementById('products').scrollIntoView({behavior:'smooth'});">Explore Products</button>
    <button class="btn" onclick="alert('Brochure download will be added soon!')">Download Brochure</button>
  </section>

  <section id="about">
    <div class="card">
      <h2>About Us</h2>
      <p>SkillStack India is a digital empowerment initiative helping individuals and small businesses go online easily.</p>
      <p><b>Mission:</b> To make digital tools accessible, affordable & understandable for everyone.</p>
      <p><b>Vision:</b> A self-reliant, tech-enabled India where every skill finds a global stage.</p>
      <p style="font-style:italic;">“Empowering Skills, Empowering India.”</p>
    </div>
  </section>

  <section id="products">
    <div class="card">
      <h2>Our Digital Products</h2>
      <ul style="list-style:none;padding:0;">
        <li>📘 Learning Guides (PDF)</li>
        <li>🎨 Canva Templates for Branding</li>
        <li>📊 Excel & Notion Productivity Tools</li>
        <li>🚀 Startup Launch Checklists</li>
      </ul>
      <br>
      <button class="btn" onclick="alert('Brochure link coming soon!')">Download Brochure</button>
    </div>
  </section>

  <section id="contact">
    <div class="card">
      <h2>Contact Us</h2>
      <p>We’d love to hear from you! Write to us for collaborations or feedback.</p>
      <p><b>Email:</b> skillstack.india@gmail.com</p>
      <p><b>Founder:</b> Himanshu Vaghela</p>
    </div>
  </section>

  <footer>
    <p>© 2025 SkillStack India | Founded by Himanshu Vaghela | Empowering Digital Growth</p>
  </footer>
</body>
</html>
